# Optional
ACCELERATOR_IDS:
    '0d5c': 
        'Intel(R) vRAN ACC100 Adpr' 
    '0d8f': 
        'Intel(R) FPGA PAC N3000'
    '0b30':
        'Intel(R) FPGA PAC N3000'
    '0b32':
        'Intel(R) FPGA PAC N3000'